### ISSUE TITLE
Looking forward to support the CY8CKIT-043...

### ISSUE THREAD

**Issue by comcat** [cypresssemiconductorco/Firmware-loader#2]
Seems like they use the same chip ....

**Comment by JimTrudeau** [comment]
Hi Jack. I'm not sure what you mean by "support." here. But I think I can answer your question.

In OpenOCD, support for the PSoC 4200M was added by the community, not Cypress. So although not managed by Cypress, support exists.

We have no immediate plans to support this kit with the current KitProg3 and Firmware Loader. The kit uses a much older version of our firmware, KitProg1. The firmware loader tool does not support KitProg1.

**Comment by JimTrudeau** [comment]
I'm going to assume the answer resolved your question. Thanks for asking.
